require "rhinocatalog/api/engine"
module Rhinocatalog
	module Api
		ERROR_ACCESS_DENIED = "ERROR_ACCESS_DENIED"
		ERROR_ACCESS_DENIED_INVALID_API_TOKEN = "ERROR_ACCESS_DENIED_INVALID_API_TOKEN"
		ERROR_ACCESS_DENIED_USER_WASNT_APPROVED = "ERROR_ACCESS_DENIED_USER_WASNT_APPROVED"
		ERROR_USER_VALIDATION_ERROR = "ERROR_USER_VALIDATION_ERROR"
		ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND"
		ERROR_PASSWORD_MISMATCH = "ERROR_PASSWORD_MISMATCH"
		ERROR_UNKNOWN_SETTING_ID = "ERROR_UNKNOWN_SETTING_ID"
		ERROR_FILE_VALIDATION_ERROR = "ERROR_FILE_VALIDATION_ERROR"
		ERROR_ACCESS_DENIED_USER_HAS_NO_ACCESS_RIGHT = "ERROR_ACCESS_DENIED_USER_HAS_NO_ACCESS_RIGHT"
		ERROR_PARAM_TYPE = "ERROR_PARAM_TYPE"
		ERROR_FILE_NOT_FOUND = "ERROR_FILE_NOT_FOUND"
		ERROR_CONTENT_NOT_FOUND = "ERROR_CONTENT_NOT_FOUND"
		ERROR_DOMAIN_NOT_FOUND = "ERROR_DOMAIN_NOT_FOUND"
	end
end